### ISSUE TITLE
problems with migrate

### ISSUE THREAD

**Issue by marcofog** [alnuaimi94/ProductFolio#1]
when i do python manage.py migrate
it give error: ...
File "C:\Users\d5871\Documents\_Wip\SviluppoWeb\200705_productfolio\ProductFolio\venv\lib\site-packages\decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

**Comment by alnuaimi94** [comment]
Yes, the solution is to comment the Production class in settings.py file,
or create .env file in the root of the project and add SECRET_KEY=somthinghere

**Comment by marcofog** [comment]
Thanks!
Marco


Il giorno dom 5 lug 2020 alle ore 10:16 Abdullah Alnuaimi <
notifications@github.com> ha scritto:
